[TSP Migration]--elastic (#34324)
* newly converted

* compiled

* update

* formatted

* prettier

* suppress some warnings

* Update models.tsp

* update

* examples update

* optional body fix and other diff fix

* justification

* remove previous api version example files

* recovery of previous api version files

* Fix addtional model  Azure.ResourceManager.ArmResponse<ElasticMonitorResource>

* Update java config

* update

* update

* prettier

* Remove Bodyboot Decorator

* resolve breaking

* update

* fix go breaking

* fix as description

System.ArgumentException: 'An item with the same key has already been added. Key: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}'

* update

* update

* fix OkResponse issue for SDK generation

* update

* Java SDK migration: Fix createAndAssociateIpFilters operation name for backward compatibility

* Update tspconfig.yaml

* update client settings

* Update main.tsp

* Update models.tsp

* update

* Update tspconfig.yaml

---------

Co-authored-by: Xiaofei Cao <92354331+XiaofeiCao@users.noreply.github.com>
Co-authored-by: Jiao Di (MSFT) <80496810+v-jiaodi@users.noreply.github.com>
Co-authored-by: melina5656 <140602263+melina5656@users.noreply.github.com>
Co-authored-by: Pan Shao <pashao@microsoft.com>
Co-authored-by: tadelesh <chenjieshi@microsoft.com>
Co-authored-by: Arthur Ma <mars.arthur@263.net>
Co-authored-by: Weidong Xu <weidxu@microsoft.com>
Co-authored-by: Arthur Ma <arthurma@microsoft.com>
Co-authored-by: Pan Shao <97225342+pshao25@users.noreply.github.com>