Enabling only reservation Apis (removing quota.json) to check, if base_url conflict is coming due to 2 json files.
TypeError: __init__() got multiple values for argument 'base_url'