fix for as description and migration language scop decorator to client.tsp
System.ArgumentException: 'An item with the same key has already been added. Key: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}'