Removed Additional ref to subscriptionId: causing error
On original PR, I failed to remove the reference to: 
SubscriptionIdParameter

I re-ran the autorest codegen test and found that it was causing error: 

error: [FATAL] Error generating client model: Reference specifies the definition SubscriptionIdParameter that does not exist.

This resolves the error, and the code generates properly now.