fix as description
System.ArgumentException: 'An item with the same key has already been added. Key: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}'